trigger:
- none

variables:
- name: RUN_SUBSCRIPTION
  value: $[ split(variables.CLUSTER_RESOURCE_ID, '/')[2] ]
- name: RUN_RESOURCEGROUP
  value: $[ split(variables.CLUSTER_RESOURCE_ID, '/')[4] ]
- name: RUN_RESOURCENAME
  value: $[ split(variables.CLUSTER_RESOURCE_ID, '/')[8] ]
- name: RUN_SCHEDULED_AT
  value: $[ replace(variables.SCHEDULED_AT_UTC,':', '-') ]

# pipeline run name is set to the following format
name: $(RUN_SCHEDULED_AT)_$(RUN_SUBSCRIPTION)_$(RUN_RESOURCEGROUP)_$(RUN_RESOURCENAME)_$(UPGRADE_VERSION)
appendCommitMessageToRunName: false

pool:
  vmImage: ubuntu-latest

stages:
- stage: scheduling
  displayName: Scheduling
  jobs:
  - job: s1
    displayName: Show resource id
    steps:
    - script: |
        echo "Resource Id: $(CLUSTER_RESOURCE_ID)"
        STAGE="$(System.StageName)"
        echo "STAGE ${STAGE}"
    - script: |
        echo "Stage: ${SYSTEM_STAGENAME}"
        echo "StageName: ${STAGENAME}"
      env:
        STAGENAME: $(System.StageName)
