name: Run upgrade scheduler

on:
  workflow_dispatch:

jobs: 
  check-upgrade-schedules:
    permissions:
      actions: write # required to trigger another workflow
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: check upgrade schedules
      shell: bash
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./check-schedule.sh