name: Upgrade scheduler

on:
  workflow_dispatch:

jobs: 
  test:
    permissions:
      id-token: write # required for authenticate to Azure using OIDC token. 
                      # https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect
      actions: write # required to trigger another workflow

    runs-on: ubuntu-latest
    steps:
    - name: invoke upgrade-cluster workflow
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'upgrade-cluster.yaml',
            ref: 'master',
            inputs: {
              cluster_resource_id: 'aks-cilium',
              target_version: '1.30.0'
            }
          });

    # - name: Azure CLI Login
    #   uses: azure/login@v2
    #   with:
    #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    # - name: Azure CLI script
    #   uses: azure/cli@v2
    #   with:
    #     azcliversion: latest
    #     inlineScript: |
    #       az account show
    #       # You can write your Azure CLI inline scripts here.
