name: Upgrade scheduler

on:
  workflow_dispatch:

jobs: 
  test:
    permissions:
      id-token: write # required for authenticate to Azure using OIDC token. 
                      # https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect
      actions: write # required to trigger another workflow

    runs-on: ubuntu-latest
    steps:
    - name: invoke upgrade-cluster workflow
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'upgrade-cluster.yaml',
            ref: 'master',
            inputs: {
              cluster_resource_id: '/subscriptions/d17e2897-3940-4fc2-9ce2-e6689837c2a7/resourcegroups/aks-lab/providers/Microsoft.ContainerService/managedClusters/aks-cilium',
              target_version: '1.31.8'
            }
          });
