name: Upgrade Cluster

on:
  workflow_dispatch:
    inputs:
      cluster_resource_id:
        required: true
        description: 'Resource id of cluster to upgrade'
      target_version:
        required: true
        description: 'target version to upgrade to'

run-name: Upgrade ${{ github.event.inputs.cluster_resource_id }} 

jobs: 
  test:
    permissions:
      id-token: write # required for authenticate to Azure using OIDC token. 
                      # https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect

    runs-on: ubuntu-latest
    steps:
    - name: print parameters
      shell: bash
      run: |
        echo "======================================================"
        echo "start upgrade-cluster.yaml workflow"
        echo "- cluster_resource_id: " ${{ github.event.inputs.cluster_resource_id }}
        echo "- target_version: " ${{ github.event.inputs.target_version }} 

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          # You can write your Azure CLI inline scripts here.
