name: Upgrade Cluster -  ${{ github.event.inputs.cluster_name }}

on:
  workflow_dispatch:
    inputs:
      cluster_resource_id:
        required: true
        description: 'Resource id of cluster to upgrade'
      target_version:
        required: true
        description: 'target version to upgrade to'

jobs: 
  test:
    permissions:
      id-token: write # required for authenticate to Azure using OIDC token. 
                      # https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect

    runs-on: ubuntu-latest
    steps:
    # print hello world using bash shell
    - name: Print Hello World
      shell: bash
      run: echo "Hello World" && sleep 180
